development:
  access_key_id: AKIAIYFCYD4NM2SWXCPQ
  secret_access_key: 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
  bucket: skillz_dev
  max_file_size: 10485760
  acl: public-read

# Use when testing a production db pull
#development:
#  access_key_id: AKIAIYFCYD4NM2SWXCPQ
#  secret_access_key: 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
#  bucket: skillz

test:
  access_key_id: AKIAIYFCYD4NM2SWXCPQ
  secret_access_key: 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
  bucket: skillz_test
  max_file_size: 10485760
  acl: public-read

staging:
  access_key_id: AKIAIYFCYD4NM2SWXCPQ
  secret_access_key: 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
  bucket: homecca_staging
  max_file_size: 10485760
  acl: public-read

production:
  access_key_id: AKIAIYFCYD4NM2SWXCPQ
  secret_access_key: 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
  bucket: skillz
  max_file_size: 10485760
  acl: public-read
